#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CANONICAL_FILE="$ROOT_DIR/ai/CONSTRAINTS.md"

if [[ ! -f "$CANONICAL_FILE" ]]; then
  echo "missing canonical constraints file: $CANONICAL_FILE" >&2
  exit 1
fi

render() {
  local tool_name="$1"
  local out_file="$2"

  cat >"$out_file" <<EOF_INNER
# ${tool_name} Instructions

> Auto-generated by scripts/sync-ai-constraints.sh.
> Do not edit this file directly.

EOF_INNER

  cat "$CANONICAL_FILE" >>"$out_file"
}

render "Codex" "$ROOT_DIR/AGENTS.md"
render "Claude Code" "$ROOT_DIR/CLAUDE.md"
render "Gemini" "$ROOT_DIR/GEMINI.md"

if command -v shasum >/dev/null 2>&1; then
  shasum -a 256 "$CANONICAL_FILE" "$ROOT_DIR/AGENTS.md" "$ROOT_DIR/CLAUDE.md" "$ROOT_DIR/GEMINI.md" >"$ROOT_DIR/ai/.constraints.sha256"
elif command -v sha256sum >/dev/null 2>&1; then
  sha256sum "$CANONICAL_FILE" "$ROOT_DIR/AGENTS.md" "$ROOT_DIR/CLAUDE.md" "$ROOT_DIR/GEMINI.md" >"$ROOT_DIR/ai/.constraints.sha256"
else
  echo "warning: no sha256 tool found, skip checksum generation" >&2
fi

echo "synced constraints for Codex/Claude/Gemini"
